### ISSUE TITLE
Runtime error during splitting

### ISSUE THREAD

**Issue by tgulacsi** [pdfcpu/pdfcpu#181]
v0.3.2 on some pdf.Split call panics
```
panic: runtime error: invalid memory address or nil pointer dereference 14f636045acb4ecdcead931afd8e2151e363146
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x972244]
goroutine 39 [running]:
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.logWriteStats(0xc000168c30)
/home/tgulacsi/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.3.2/pkg/pdfcpu/writeStats.go:35 +0xbd4
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.Write(0xc000168c30, 0x0, 0x0)
/home/tgulacsi/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.3.2/pkg/pdfcpu/write.go:138 +0x753
github.com/pdfcpu/pdfcpu/pkg/api.writeSpan(0xc000168c30, 0x1, 0x1, 0xc0000f0240, 0x3b, 0xc0000f1f22, 0x1c, 0x5e9722bf, 0xc03a4461b0)
/home/tgulacsi/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.3.2/pkg/api/api.go:544 +0x17b
github.com/pdfcpu/pdfcpu/pkg/api.writePDFSequence(0xc000168c30, 0x1, 0xc0000f0240, 0x3b, 0xc0000f1f22, 0x1c, 0xc000168c30, 0x0)
/home/tgulacsi/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.3.2/pkg/api/api.go:554 +0xf3
github.com/pdfcpu/pdfcpu/pkg/api.Split(0xd6a400, 0xc00016f928, 0xc0000f0240, 0x3b, 0xc0000f1f22, 0x1c, 0x1, 0xc0000ee480, 0x4dddc0, 0xc0000dbad8)
/home/tgulacsi/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.3.2/pkg/api/api.go:596 +0x199
github.com/pdfcpu/pdfcpu/pkg/api.SplitFile(0xc0000f1f00, 0x3e, 0xc0000f0240, 0x3b, 0x1, 0xc0000ee480, 0x0, 0x0)
/home/tgulacsi/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.3.2/pkg/api/api.go:620 +0x1f2
github.com/tgulacsi/go/pdf.Split(...)
/home/tgulacsi/go/pkg/mod/github.com/tgulacsi/go@v0.11.2/pdf/pdf.go:46
```

Why does XRefTable return a *string? A string is already a pointer...
Why does not check it in logWriteStats? If missing==0 then str==nil.

**Comment by hhrutter** [comment]
Thanks for discovering this!

Using string pointers was an opinionated design choice right at the beginning of this project.

**Comment by hhrutter** [comment]
Fixing a symptom is one thing but we need to get to the root of this.
Something is going wrong when analyzing the cross reference table for missing objects.

Can you please share *a* or *the* PDF that caused this problem?

Also does this file give you a validation error when you execute:
`pdfcpu val theFile.pdf` ?

**Comment by tgulacsi** [comment]
Ok, I've got the PDF. Using v0.3.2, 
It has 2 pages and validates:

```
! pdfcpu val -v -mode strict pdf-cannot-split.pdf
validating(mode=strict) pdf-cannot-split.pdf ...
 INFO: 2020/04/16 10:57:15 PDF Version 1.5 conforming reader
 INFO: 2020/04/16 10:57:15 validating
STATS: 2020/04/16 10:57:15 XRefTable:
%!s(PANIC=String method: runtime error: invalid memory address or nil pointer dereference)
STATS: 2020/04/16 10:57:15 Timing:
STATS: 2020/04/16 10:57:15 read                 :  0.003s  85.2%
STATS: 2020/04/16 10:57:15 validate             :  0.000s  14.8%
STATS: 2020/04/16 10:57:15 total processing time:  0.003s

STATS: 2020/04/16 10:57:15 Original:
STATS: 2020/04/16 10:57:15 File Size            : 0.000000 Bytes (0 bytes)
STATS: 2020/04/16 10:57:15 Total Binary Data    : 1.0 MB (1067454 bytes) +Inf%
STATS: 2020/04/16 10:57:15 Total Text   Data    : -1067454.000000 Bytes (-1067454 bytes) -Inf%

validation ok
```

but pdfcpi cannot split it:
```
$ mkdir x; pdfcpu split -v pdf-cannot-split.pdf x
splitting pdf-cannot-split.pdf to x/...
 INFO: 2020/04/16 10:58:20 PDF Version 1.5 conforming reader
 INFO: 2020/04/16 10:58:20 validating
 INFO: 2020/04/16 10:58:20 optimizing fonts & images
 INFO: 2020/04/16 10:58:20 writing to x/pdf-cannot-split_1.pdf
Fatal: unexpected panic attack: runtime error: invalid memory address or nil pointer dereference

github.com/pdfcpu/pdfcpu/pkg/cli.Process.func1
        /home/tgulacsi/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.3.2/pkg/cli/process.go:96
runtime.gopanic
        /usr/local/go/src/runtime/panic.go:969
runtime.panicmem
        /usr/local/go/src/runtime/panic.go:212
runtime.sigpanic
        /usr/local/go/src/runtime/signal_unix.go:695
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.logWriteStats
        /home/tgulacsi/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.3.2/pkg/pdfcpu/writeStats.go:35
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.Write
        /home/tgulacsi/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.3.2/pkg/pdfcpu/write.go:138
github.com/pdfcpu/pdfcpu/pkg/api.writeSpan
        /home/tgulacsi/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.3.2/pkg/api/api.go:544
github.com/pdfcpu/pdfcpu/pkg/api.writePDFSequence
        /home/tgulacsi/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.3.2/pkg/api/api.go:554
github.com/pdfcpu/pdfcpu/pkg/api.Split
        /home/tgulacsi/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.3.2/pkg/api/api.go:596
github.com/pdfcpu/pdfcpu/pkg/api.SplitFile
        /home/tgulacsi/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.3.2/pkg/api/api.go:620
github.com/pdfcpu/pdfcpu/pkg/cli.Split
        /home/tgulacsi/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.3.2/pkg/cli/cli.go:79
github.com/pdfcpu/pdfcpu/pkg/cli.Process
        /home/tgulacsi/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.3.2/pkg/cli/process.go:103
main.process
        /home/tgulacsi/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.3.2/cmd/pdfcpu/main.go:105
main.handleSplitCommand
        /home/tgulacsi/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.3.2/cmd/pdfcpu/prepare.go:148
main.CommandMap.Handle
        /home/tgulacsi/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.3.2/cmd/pdfcpu/registry.go:85
main.main
        /home/tgulacsi/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.3.2/cmd/pdfcpu/main.go:61
runtime.main
        /usr/local/go/src/runtime/proc.go:203
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1373
```

**Comment by tgulacsi** [comment]
With
```
diff --git a/pkg/pdfcpu/writeStats.go b/pkg/pdfcpu/writeStats.go
index 1b0c339..e3b85ac 100644
--- a/pkg/pdfcpu/writeStats.go
+++ b/pkg/pdfcpu/writeStats.go
@@ -32,7 +32,11 @@ func logWriteStats(ctx *Context) {

        if len(xRefTable.Table) != *xRefTable.Size {
                missing, str := xRefTable.MissingObjects()
-               log.Stats.Printf("%d missing objects: %s\n", missing, *str)
+               var s string
+               if str != nil {
+                       s = *str
+               }
+               log.Stats.Printf("%d missing objects: %s\n", missing, s)
        }

        var nonRefObjs []int
```
patch it works.

**Comment by tgulacsi** [comment]
But I'd change MissingObjects to never return a nil *string.
