### ISSUE TITLE
Stamp API: panic: assignment to entry in nil map

### ISSUE THREAD

**Issue by pallavagarwal07** [pdfcpu/pdfcpu#340]
Trace:

```
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.(*Context).createForm(0xc0000a0540, 0x12, 0x16, 0xc000d2c000, 0xc00007a000, 0x0, 0x0)
	external/com_github_pdfcpu_pdfcpu/pkg/pdfcpu/stamp.go:1483 +0x825
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.(*Context).addPageWatermark(0xc0000a0540, 0x12, 0xc000d2c000, 0xc02f81e6e0, 0x1)
	external/com_github_pdfcpu_pdfcpu/pkg/pdfcpu/stamp.go:1786 +0x1aa
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.(*Context).AddWatermarksMap(0xc0000a0540, 0xc0005040c0, 0x1281300, 0xc025b6cd25d50816)
	external/com_github_pdfcpu_pdfcpu/pkg/pdfcpu/stamp.go:1930 +0x4c6
github.com/pdfcpu/pdfcpu/pkg/api.AddWatermarksMap(0xe42d88, 0xc0001fe020, 0xe3de98, 0xc0001fe028, 0xc0005040c0, 0xc01fef4b00, 0x0, 0xc000490d40)
	external/com_github_pdfcpu_pdfcpu/pkg/api/stamp.go:53 +0x1f9
github.com/pdfcpu/pdfcpu/pkg/api.AddWatermarksMapFile(0xc000042dc0, 0x37, 0xc000042e00, 0x36, 0xc0005040c0, 0x0, 0x0, 0x0)
	external/com_github_pdfcpu_pdfcpu/pkg/api/stamp.go:118 +0x30f
main.main()
	utility/pdf/main.go:130 +0x71f
```

Seems to be happening due to the unexported field fCache not being initialized. I am manually creating the watermark struct for `AddWatermarksMapFile`.

I can get around the issue for now by using pdfcpu.DefaultWatermarkConfig() and then manually overriding each field.

**Comment by hhrutter** [comment]
Hello!

Please show me your code so I can assess if you are using the API properly.

**Comment by pallavagarwal07** [comment]
Minimal example to reproduce:

```
package main

import (
  "log"

  "github.com/pdfcpu/pdfcpu/pkg/api"
  "github.com/pdfcpu/pdfcpu/pkg/pdfcpu"
)

func main() {
  watermarks := map[int]*pdfcpu.Watermark{}
  config := &pdfcpu.Watermark{
    Mode:              pdfcpu.WMImage,
    Pos:               pdfcpu.TopLeft,
    Scale:             1.0,
    FileName:          "image.png",
    OnTop:             true,
    Rotation:          0,
    Diagonal:          pdfcpu.NoDiagonal,
    UserRotOrDiagonal: true,
    Opacity:           1,
  }
  watermarks[1] = config
  err := api.AddWatermarksMapFile("sample.pdf", "output.pdf", watermarks, nil)
  if err != nil {
    log.Fatalln(err)
  }
}
```



The following works:

```
package main

import (
	"log"

	"github.com/pdfcpu/pdfcpu/pkg/api"
	"github.com/pdfcpu/pdfcpu/pkg/pdfcpu"
)

func main() {
	watermarks := map[int]*pdfcpu.Watermark{}
	config := pdfcpu.DefaultWatermarkConfig()
	config.Mode = pdfcpu.WMImage
	config.Pos = pdfcpu.TopLeft
	config.Scale = 1.0
	config.FileName = "image.png"
	config.OnTop = true
	config.Rotation = 0
	config.Diagonal = pdfcpu.NoDiagonal
	config.UserRotOrDiagonal = true
	config.Opacity = 1
	watermarks[1] = config
	err := api.AddWatermarksMapFile("sample.pdf", "output.pdf", watermarks, nil)
	if err != nil {
		log.Fatalln(err)
	}
}
```

**Comment by hhrutter** [comment]
ok I will check.

**Comment by hhrutter** [comment]
Hi!

You are supposed to create your Watermark via: 

`wm, err := api.TextWatermark(text, desc, true, false, pdfcpu.POINTS)`

like in [stampVersatile_test.go](https://github.com/pdfcpu/pdfcpu/blob/master/pkg/api/test/stampVersatile_test.go)

**Comment by hhrutter** [comment]
Closed due to inactivity.
