### ISSUE TITLE
runtime error: index out of range [92] with length 92

### ISSUE THREAD

**Issue by heggiz** [pdfcpu/pdfcpu#589]
Hello,

I encountered a panic while fuzzing one of our services which accepts user uploaded pdfs:

```
--- FAIL: FuzzValidate (0.05s)
    --- FAIL: FuzzValidate (0.00s)
        testing.go:1485: panic: runtime error: index out of range [92] with length 92
            goroutine 31 [running]:
            runtime/debug.Stack()
            	/usr/local/go/src/runtime/debug/stack.go:24 +0x9e
            testing.tRunner.func1()
            	/usr/local/go/src/testing/testing.go:1485 +0x1f6
            panic({0xabb620, 0xc00017c210})
            	/usr/local/go/src/runtime/panic.go:884 +0x213
            github.com/pdfcpu/pdfcpu/pkg/pdfcpu.headerVersion({0xb9a820?, 0xc00011b9e0}, 0x64)
            	/home/runar/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.4.1-0.20230312101853-a410fdc32533/pkg/pdfcpu/read.go:1177 +0x7e5
            github.com/pdfcpu/pdfcpu/pkg/pdfcpu.buildXRefTableStartingAt(0xc00011bef0, 0xc00011d0c0)
            	/home/runar/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.4.1-0.20230312101853-a410fdc32533/pkg/pdfcpu/read.go:1351 +0x126
            github.com/pdfcpu/pdfcpu/pkg/pdfcpu.readXRefTable(0xc00011bef0)
            	/home/runar/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.4.1-0.20230312101853-a410fdc32533/pkg/pdfcpu/read.go:1422 +0x15a
            github.com/pdfcpu/pdfcpu/pkg/pdfcpu.Read({0xb9a820, 0xc00011b9e0}, 0xc00011a5d0?)
            	/home/runar/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.4.1-0.20230312101853-a410fdc32533/pkg/pdfcpu/read.go:79 +0x2c5
            github.com/pdfcpu/pdfcpu/pkg/api.ReadContext(...)
            	/home/runar/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.4.1-0.20230312101853-a410fdc32533/pkg/api/api.go:51
            github.com/pdfcpu/pdfcpu/pkg/api.Validate({0xb9a820, 0xc00011b9e0}, 0x4?)
            	/home/runar/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.4.1-0.20230312101853-a410fdc32533/pkg/api/validate.go:43 +0x1db
            pdfcpu.FuzzValidate.func1(0xc000102d00, {0xc000124c00, 0x200, 0x200})
            	/home/runar/Development/socialscreen/pdfcpu/fuzz_test.go:21 +0xa9
            reflect.Value.call({0xa64d60?, 0xb2efe0?, 0x13?}, {0xae9b37, 0x4}, {0xc00011b9b0, 0x2, 0x2?})
            	/usr/local/go/src/reflect/value.go:586 +0xb07
            reflect.Value.Call({0xa64d60?, 0xb2efe0?, 0xd7bdc8?}, {0xc00011b9b0?, 0xae7d60?, 0xc00011d0b8?})
            	/usr/local/go/src/reflect/value.go:370 +0xbc
            testing.(*F).Fuzz.func1.1(0x0?)
            	/usr/local/go/src/testing/fuzz.go:335 +0x3f3
            testing.tRunner(0xc000102d00, 0xc00012c750)
            	/usr/local/go/src/testing/testing.go:1576 +0x10b
            created by testing.(*F).Fuzz.func1
            	/usr/local/go/src/testing/fuzz.go:322 +0x5b9
```

I'm attaching the fuzzer with the testdata that fails: 
[pdfcpu.zip](https://github.com/pdfcpu/pdfcpu/files/10978455/pdfcpu.zip)

The fuzzer can be run with this command: `go test . -fuzz=FuzzValidate`

**Comment by hhrutter** [comment]
👍 Thanks for the bug report
Fix is in the works..

**Comment by hhrutter** [comment]
This is fixed with the latest release.
