### ISSUE TITLE
Importing PDF page panics

### ISSUE THREAD

**Issue by mengstr** [pdfcpu/pdfcpu#629]
On a M1 Mac running MacOS 13.3.1(a) using  pdfcpu  v0.4.1 I get the following error when trying to import a page. I've attached the offending file for your enjoyment ;-)

It looks like it might be a problem in gopdfi - I hope this won't be an unfixable issue even if it's not been updated/maintained for the last couple of years. 

```
		pdf.AddPage()
		page := pdf.ImportPage(inFilename, i, "/MediaBox")
		pdf.UseImportedTemplate(page, 0, 0, 0, 0)
```

[BadPDF.pdf](https://github.com/pdfcpu/pdfcpu/files/11609443/BadPDF.pdf)

```
2023-05-31T08:25:18.250+0200    INFO    hm-site/main.go:207     /sign/9e5af9da-1a10-46d1-9557-450c0ba65cc0
2023-05-31T08:25:18.251+0200    INFO    hm-site/sign.go:39      signHandler(../hm-storage/sign/BadPDF.pdf)
2023-05-31T08:25:18.274+0200    DEBUG   hm-site/sign.go:45      6 pages
2023-05-31T08:25:18.280+0200    DEBUG   hm-site/sign.go:54      Importing page 1
2023/05/31 08:25:18 http: panic serving [::1]:59936: Failed to initialize parser: Failed to read pdf: Failed to read xref table: Unsupported /DecodeParms - only tested with /Columns <= 4 and /Predictor <= 12
goroutine 39 [running]:
net/http.(*conn).serve.func1()
        /opt/homebrew/Cellar/go/1.20.4/libexec/src/net/http/server.go:1854 +0xb0
panic({0x1034d0de0, 0x1400000c510})
        /opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/panic.go:890 +0x258
github.com/phpdave11/gofpdi.(*Importer).SetSourceFile(0x140005968c0, {0x1400069a420?, 0x0?})
        /Users/mats/go/pkg/mod/github.com/phpdave11/gofpdi@v1.0.14-0.20211212211723-1f10f9844311/importer.go:71 +0x188
github.com/signintech/gopdf.(*GoPdf).ImportPage(0x14000144b00, {0x1400069a420?, 0x103311248?}, 0x11?, {0x103309695, 0x9})
        /Users/mats/go/pkg/mod/github.com/signintech/gopdf@v0.17.0/gopdf.go:1377 +0x40
main.signHandler({0x103548330, 0x1400053ab60}, 0x1400059b001?)
        /Users/mats/Desktop/HealthManager/hm-site/sign.go:55 +0x338
net/http.HandlerFunc.ServeHTTP(0x14000122560?, {0x103548330?, 0x1400053ab60?}, 0x0?)
        /opt/homebrew/Cellar/go/1.20.4/libexec/src/net/http/server.go:2122 +0x38
main.loggingMiddleware.func1({0x103548330, 0x1400053ab60}, 0x1400069c100)
        /Users/mats/Desktop/HealthManager/hm-site/main.go:210 +0x174
net/http.HandlerFunc.ServeHTTP(0x140000c3f00?, {0x103548330?, 0x1400053ab60?}, 0x0?)
        /opt/homebrew/Cellar/go/1.20.4/libexec/src/net/http/server.go:2122 +0x38
github.com/gorilla/mux.(*Router).ServeHTTP(0x1400016c0c0, {0x103548330, 0x1400053ab60}, 0x140000c3d00)
        /Users/mats/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x19c
net/http.serverHandler.ServeHTTP({0x14000464600?}, {0x103548330, 0x1400053ab60}, 0x140000c3d00)
        /opt/homebrew/Cellar/go/1.20.4/libexec/src/net/http/server.go:2936 +0x2d8
net/http.(*conn).serve(0x140000a21b0, {0x103548a08, 0x140004e0a20})
        /opt/homebrew/Cellar/go/1.20.4/libexec/src/net/http/server.go:1995 +0x560
created by net/http.(*Server).Serve
        /opt/homebrew/Cellar/go/1.20.4/libexec/src/net/http/server.go:3089 +0x520
```

**Comment by hhrutter** [comment]
How is this related to pdfcpu?
Please explain!
Thank you!

**Comment by hhrutter** [comment]
Closed due to inactivity.
