### ISSUE TITLE
Out of spec Pages dict

### ISSUE THREAD

**Issue by mygityf** [pdfcpu/pdfcpu#677]
## Issue info
- based on the latest commit : master
- OS and OS version: MacBook Pro macOS 13.5(22G74)

## PDF info:
```sh
%PDF-1.2
....
36 0 obj
<<
/ModDate(D:20230818141312+08'00')
/Creator(Image Capture Plus)
/CreationDate(D:20230818110448+08'00')
/Type/Catalog
...
/Pages<</Kids[4 0 R 11 0 R 18 0 R 25 0 R 32 0 R 39 0 R]
/Type/Pages/Count 6>>>>
...
<<
/Size 43
/Root 36 0 R
/Info 36 0 R
>>
```

### test code
```golang
func TestXRefTable_PageDims(t *testing.T) {
	pdfFileName := `xRefTable.EnsurePageCount-panic.pdf`
	pdfBytes, err := os.ReadFile(pdfFileName)
	if err != nil {
		t.Error(err)
	}
	rs := bytes.NewReader(pdfBytes)
	dimList, err := PageDims(rs, model.NewDefaultConfiguration())
	if err != nil {
		t.Log(err)
	}
	t.Log(dimList)
}
```

### panic info
```sh
=== RUN   TestXRefTable_PageDims
--- FAIL: TestXRefTable_PageDims (0.01s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11a2a39]

goroutine 6 [running]:
testing.tRunner.func1.2({0x126e020, 0x14bd290})
	/usr/local/opt/go/libexec/src/testing/testing.go:1526 +0x24e
testing.tRunner.func1()
	/usr/local/opt/go/libexec/src/testing/testing.go:1529 +0x39f
panic({0x126e020, 0x14bd290})
	/usr/local/opt/go/libexec/src/runtime/panic.go:884 +0x213
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/model.(*XRefTable).EnsurePageCount(0xc0000a2000)
	/Users/yaofu/Downloads/pdfcpu-master/pkg/pdfcpu/model/xreftable.go:1954 +0x39
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/model.(*XRefTable).PageBoundaries(0xc0000a2000, 0x100d3c7?)
	/Users/yaofu/Downloads/pdfcpu-master/pkg/pdfcpu/model/xreftable.go:2145 +0x3b
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/model.(*XRefTable).PageDims(0x132fd00?)
	/Users/yaofu/Downloads/pdfcpu-master/pkg/pdfcpu/model/xreftable.go:2168 +0x2d
github.com/pdfcpu/pdfcpu/pkg/api.PageDims({0x132fd00?, 0xc0001b81b0?}, 0x599?)
	/Users/yaofu/Downloads/pdfcpu-master/pkg/api/page.go:254 +0x4a
github.com/pdfcpu/pdfcpu/pkg/api.TestXRefTable_PageDims(0xc000182b60)
	/Users/yaofu/Downloads/pdfcpu-master/pkg/api/page_test.go:18 +0xe7
testing.tRunner(0xc000182b60, 0x12f01c8)
	/usr/local/opt/go/libexec/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
	/usr/local/opt/go/libexec/src/testing/testing.go:1629 +0x3ea
```

### panic code
```golang
// EnsurePageCount evaluates the page count for xRefTable if necessary.
// Important when validation is turned off.
func (xRefTable *XRefTable) EnsurePageCount() error {

	if xRefTable.PageCount > 0 {
		return nil
	}

	pageRoot, err := xRefTable.Pages()
	if err != nil {
		return err
	}
// HERE: panic pageRoot is nil
	d, err := xRefTable.DereferenceDict(*pageRoot)
```

### poppler 
```c++
        Object obj = catDict.dictLookup("Pages");
        // This should really be isDict("Pages"), but I've seen at least one
```

**Comment by hhrutter** [comment]
Hello!

This is in violation of the PDF specification:
<img width="511" alt="Screenshot 2023-08-22 at 11 57 47" src="https://github.com/pdfcpu/pdfcpu/assets/11322155/1cc766b6-ea7e-4098-9e68-98ab7159fe6d">




Please submit a test file for further analysis in order to decide wether we can relax validation.

**Comment by mygityf** [comment]
You are right.
This PDF file format is incorrect.

<<PDF Reference 1.0.pdf>>
Table 6.1 Catalog attributes
Pages dictionary (Required, must be an indirect reference) Pages object that is the root of the document’s Pages
tree.
