### ISSUE TITLE
PDFCPU version panic

### ISSUE THREAD

**Issue by owenhankinson** [pdfcpu/pdfcpu#768]
Using Linux (ubuntu 20.04.0)

```
`pdfcpu version`
pdfcpu: v0.6.0 dev

panic: runtime error: slice bounds out of range [:8] with length 1

goroutine 1 [running]:
main.printVersion(0xc0001c1a00)
```

**Comment by owenhankinson** [comment]
Panic stack

```
goroutine 1 [running]:
main.printVersion(0xc0001c1a00)
        /home/owenhankinson/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.6.0/cmd/pdfcpu/process.go:143 +0x26e
main.commandMap.process(0x4406c5?, {0x7ffd00bb427d, 0x7}, {0x0, 0x0})
        /home/owenhankinson/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.6.0/cmd/pdfcpu/cmd.go:143 +0x342
main.main()
        /home/owenhankinson/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.6.0/cmd/pdfcpu/main.go:56 +0xaf
```

**Comment by hhrutter** [comment]
see #751
