### ISSUE TITLE
api: panic due to not properly initialized watermark struct

### ISSUE THREAD

**Issue by the-hotmann** [pdfcpu/pdfcpu#787]
This is my code:

```
package main

import (
	"bytes"
	"fmt"
	"log"
	"os"

	"github.com/pdfcpu/pdfcpu/pkg/api"
	"github.com/pdfcpu/pdfcpu/pkg/pdfcpu/model"
)

func main() {
	inputFile := "../test/input.pdf"
	outputFile := "../test/output.pdf"
	watermarkText := "Confidential - DEMO"

	if err := addWatermark(inputFile, outputFile, watermarkText); err != nil {
		log.Fatal(err)
	}

	fmt.Printf("Watermark added successfully to %s\n", outputFile)
}

func addWatermark(inputFile, outputFile, watermarkText string) error {
	// Open the input PDF file for reading
	inputFileReader, err := os.Open(inputFile)
	if err != nil {
		return err
	}
	defer inputFileReader.Close()

	// Create an output buffer to write the result
	var outputBuffer bytes.Buffer

	// Create a Watermark struct with the desired settings
	watermark := model.Watermark{
		TextString: watermarkText,
		OnTop:      true,
		Diagonal:   1,
		FontName:   "Helvetica",
	}

	// Process the PDF with the specified watermark
	if err := api.AddWatermarks(inputFileReader, &outputBuffer, nil, &watermark, nil); err != nil {
		return err
	}

	// Write the result to the output file
	outputFileWriter, err := os.Create(outputFile)
	if err != nil {
		return err
	}
	defer outputFileWriter.Close()

	_, err = outputBuffer.WriteTo(outputFileWriter)
	if err != nil {
		return err
	}

	return nil
}
```

But the line
```
api.AddWatermarks(inputFileReader, &outputBuffer, nil, &watermark, nil)
```

panics like this:

```
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.createForm(0xc0001d0030, 0x1, 0x0?, 0xc000295670, 0x0)
        /root/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.6.0/pkg/pdfcpu/stamp.go:1067 +0xc65
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.addPageWatermark(_, _, {0x1, 0x0, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...})
        /root/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.6.0/pkg/pdfcpu/stamp.go:1379 +0x2be
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.AddWatermarks(0xc0001d0030, 0xc0001d14d0, 0xc00011eb40)
        /root/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.6.0/pkg/pdfcpu/stamp.go:1639 +0x27b
github.com/pdfcpu/pdfcpu/pkg/api.AddWatermarks({0x8f1988, 0xc000052410}, {0x8f01e0, 0xc00007d920}, {0x0, 0x0, 0x0}, 0xc00011eb40, 0xc0001a3c70?)
        /root/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.6.0/pkg/api/stamp.go:253 +0x1f4
main.addWatermark({0x846966?, 0x407b4b?}, {0x84725d, 0x12}, {0x8440db, 0xc})
        /path/to/folder/go_add_pdf_watermark/PUSH/public/main.go:45 +0x1be
main.main()
        /path/to/folder/go_add_pdf_watermark/PUSH/public/main.go:18 +0x3c
exit status 2
```

I just want to take a PDF, add to all pages the watermark and later maybe line it up from bottom-left, to top-right.
I just can't seem to get why it is panicing.

Is the problem with me, or with the program?

**Comment by the-hotmann** [comment]
This seems to be related to the font.

The docs states:

> supported are Adobe base fonts only. (as of now: Helvetica, Times-Roman, Courier)

But as soon as you select them they throw an error.
Also no tutorial on how to install them on linux, if missing. Already tried to install `Helvetica` - with no success.

IMHO: the tutorials are quite bad. Or maybe I am not clever enough to make use of the most of it (so that it works).

**Comment by the-hotmann** [comment]
I added this functionality:

```
availableFonts, err := api.ListFonts()
if err != nil {
	return err
}

fmt.Println(availableFonts)
```

It clearly prints:

```
[Corefonts:   Courier   Courier-Bold   Courier-BoldOblique   Courier-Oblique   Helvetica   Helvetica-Bold   Helvetica-BoldOblique   Helvetica-Oblique   Symbol   Times-Bold   Times-BoldItalic   Times-Italic   Times-Roman   ZapfDingbats  Userfonts():]
```

But when using any of these FontNames, it failes as shown above.

**Comment by hhrutter** [comment]
Nope, this won't work..

I am sure you already have familiarized yourself with the codebase.
There is plenty of tests which should get you going: ..api/test/stamp_test.go

Other than that I have a full time job and putting in late night hours to maintain and move pdfcpu forward.
If you don't like what you see, please move on and complain to other maintainers who give stuff away free in their spare time.

Thank you for using pdfcpu 💚
