### ISSUE TITLE
runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by mdfgzh** [pdfcpu/pdfcpu#853]
### I need to fill in Chinese characters into the form, but when I installed the font and filled it in, a panic error occurred. Is my usage method incorrect? Hope you can get the answer, thank you.

**This is my code：**
```
func TestFillFormFile(t *testing.T) {
	fontFiles := []string{"SIMSUN.ttf"}
	font.UserFontDir = "C:\\Users\\mdf\\Desktop\\git\\gitlab\\blockchain\\test\\font"
	err := api.InstallFonts(fontFiles)
	if err != nil {
		fmt.Println("An error occurred while installing fonts：", err)
		return
	}
	fmt.Println("Successful installation！")
	err = api.FillFormFile("ebCert.pdf", "ebCert.json", "ebCert_new.pdf", nil)
	if err != nil {
		println(err.Error())
		return
	}
}
```

**This is log：**
```
=== RUN   TestFillFormFile
Successful installation！
--- FAIL: TestFillFormFile (0.09s)
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0

goroutine 6 [running]:
testing.tRunner.func1.2({0x56e7c0, 0xc00001f218})
	C:/Program Files/Go/src/testing/testing.go:1545 +0x238
testing.tRunner.func1()
	C:/Program Files/Go/src/testing/testing.go:1548 +0x397
panic({0x56e7c0?, 0xc00001f218?})
	C:/Program Files/Go/src/runtime/panic.go:914 +0x21f
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/font.Lang(0xc0000282ac?, 0x6?)
	C:/Users/mdf/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.7.0/pkg/pdfcpu/font/fontDict.go:1087 +0x1b6
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/primitives.FormFontNameAndLangForID(0x0?, {0x18, 0x0})
	C:/Users/mdf/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.7.0/pkg/pdfcpu/primitives/font.go:155 +0xbe
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/primitives.extractFormFontDetails(0xc0001e0ea0, {0xc00001e5a1, 0x6}, 0x0?)
	C:/Users/mdf/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.7.0/pkg/pdfcpu/primitives/font.go:366 +0x8f
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/primitives.(*TextField).calcFontFromDA(0xc00035cfc0, 0xc0001e0ea0, 0x4?, 0x1, 0x0?)
	C:/Users/mdf/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.7.0/pkg/pdfcpu/primitives/textField.go:243 +0x26e
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/primitives.NewTextField(0xc0001e0ea0, 0x59f361?, {0xc00036b170, 0x9}, 0x0, 0x0, 0x0?)
	C:/Users/mdf/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.7.0/pkg/pdfcpu/primitives/textField.go:898 +0x318
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/primitives.renderTextFieldAP(0xc0001e0ea0, 0x59f361?, {0xc00036b170, 0x9}, 0xd0?, 0xedc85?)
	C:/Users/mdf/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.7.0/pkg/pdfcpu/primitives/textField.go:932 +0xad
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/primitives.EnsureTextFieldAP(0xc0001e0ea0, 0x59fda3?, {0xc00036b170, 0x9}, 0x0?, 0x592dc0?)
	C:/Users/mdf/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.7.0/pkg/pdfcpu/primitives/textField.go:955 +0x74c
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/form.fillTextField(0xc0001e0ea0, 0xc00036b280?, {0x5cbbf7?, 0xc000367750?}, {0xc00036b248?, 0x8?}, {0x0, 0x0}, 0x0, 0x1, ...)
	C:/Users/mdf/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.7.0/pkg/pdfcpu/form/fill.go:950 +0x285
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/form.fillTx(0xc0001e0ea0, 0x9?, {0x5cbbf7, 0x2}, {0xc00036b248, 0x4}, 0xc0?, 0xc0001e1d40?, 0x5a0bb0?, 0xc000367d28, ...)
	C:/Users/mdf/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.7.0/pkg/pdfcpu/form/fill.go:987 +0x1ee
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/form.fillWidgetAnnots(0xc0001e0ea0, {0xc000591d00, 0x9, 0x10}, 0x5?, {0xc0001df158?, 0xc0003083f0?}, 0xf1b?, 0x0?, 0xc000367d28, ...)
	C:/Users/mdf/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.7.0/pkg/pdfcpu/form/fill.go:1050 +0x346
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/form.FillForm(0xc0001e0ea0, 0x9?, 0x0, 0x0?)
	C:/Users/mdf/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.7.0/pkg/pdfcpu/form/fill.go:1090 +0x20b
github.com/pdfcpu/pdfcpu/pkg/api.FillForm({0x660a18?, 0xc0003a4128?}, {0x65f240, 0xc0003a4120}, {0x65f200, 0xc0003a4130}, 0xc000112500?)
	C:/Users/mdf/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.7.0/pkg/api/form.go:543 +0x32e
github.com/pdfcpu/pdfcpu/pkg/api.FillFormFile({0x5a2adc, 0xa}, {0x5a360a?, 0x1?}, {0x5a547d, 0xe}, 0x5ac?)
	C:/Users/mdf/go/pkg/mod/github.com/pdfcpu/pdfcpu@v0.7.0/pkg/api/form.go:606 +0x2fc
blockchain/test.TestFillFormFile(0x0?)
	C:/Users/mdf/Desktop/git/gitlab/blockchain/test/pdf_test.go:76 +0x148
testing.tRunner(0xc00005fd40, 0x5e7300)
	C:/Program Files/Go/src/testing/testing.go:1595 +0xff
created by testing.(*T).Run in goroutine 1
	C:/Program Files/Go/src/testing/testing.go:1648 +0x3ad
```

**Comment by hhrutter** [comment]
Did you check if your pdf file is valid as far as pdfcpu is concerned?
`pdfcpu val ebCert.pdf`

Also I would not add a user font on the fly instead do it separately and ensure it can be loaded prior to using it using the API.

In any case if you can share your file I can take a look and provide a fix.

**Comment by mdfgzh** [comment]
[ebCert.pdf](https://github.com/pdfcpu/pdfcpu/files/15051175/ebCert.pdf)
@hhrutter thank you

**Comment by hhrutter** [comment]
Hello!
Filling a form using a specific font is still an open issue.
See also #715 and #825

**Comment by hhrutter** [comment]
This is fixed with the latest commit!
Your filling with SimSun will work since your input file is already prepared with Textfields expected to be filled with SimSun.
Specifying a fill font when filling remains an open issue.

**Comment by mdfgzh** [comment]
> This is fixed with the latest commit! Your filling with SimSun will work since your input file is already prepared with Textfields expected to be filled with SimSun. Specifying a fill font when filling remains an open issue.

@hhrutter Thank you for your efforts. However, I used V0.8.0 to fill, but it still reported an error. Is there something wrong with the font I used?

**Comment by hhrutter** [comment]
Just go get the latest commit and it will work.

**Comment by mdfgzh** [comment]
> Just go get the latest commit and it will work.

Thank you for your efforts, but I have another question. When I open the PDF file generated after filling, the Chinese fonts cannot be displayed normally, either not displayed or garbled. When I click on the corresponding form field, the fonts are displayed normally. Is this because the fonts are not embedded correctly?

**Comment by hhrutter** [comment]
Which PDF Viewer are you using.
Try Acrobat Reader.
Please also attach some screen shots.

**Comment by hhrutter** [comment]
Please test the following and let me know how that goes.
If this fails, please post the edited out.json so I can reproduce the result:
```
pdfcpu font install simsun.ttf
pdfcpu form fill ebCert.pdf ebCert.json out.pdf
```

**Comment by dingyaguang117** [comment]
> Which PDF Viewer are you using. Try Acrobat Reader. Please also attach some screen shots.

Hi Rutter, Meet same problem when using Microsoft Yahei for filling pdf with Chinese. Can't display in Adobe Arcrobat.

**Comment by hhrutter** [comment]
In PDF you can embed subset of fonts, but that does not work for the form font - the form that is used to fill text fields.
CJK font files are big usually because of the number of glyphs involved.

I have a question, since you seem to be a member of the Chinese pdfcpu user community..

Can you tell me if Chinese / CJK PDF forms usually have the form font embedded or not?

A more general question would be: In which cases have chinese PDFs the form embedded or not?

Thank you!

**Comment by mdfgzh** [comment]
> In PDF you can embed subset of fonts, but that does not work for the form font - the form that is used to fill text fields.在 PDF 中，您可以嵌入字体子集，但这不适用于表单字体 - 用于填充文本字段的表单。 CJK font files are big usually because of the number of glyphs involved.CJK 字体文件很大，通常是因为涉及的字形数量众多。
> 
> I have a question, since you seem to be a member of the Chinese pdfcpu user community..我有一个问题，因为您似乎是中国pdfcpu用户社区的成员。.
> 
> Can you tell me if Chinese / CJK PDF forms usually have the form font embedded or not?您能告诉我中文/ CJK PDF表格通常是否嵌入了表单字体吗？
> 
> A more general question would be: In which cases have chinese PDFs the form font embedded or not?一个更普遍的问题是：在哪些情况下，中文PDF的表单字体是否嵌入？
> 
> Do you think you can share a sample of a filled CJK PDF form, maybe filled in Acrobat or some other tool you prefer to use? Maybe 2 files, the empty form and the filled form.您是否认为您可以分享已填写的 CJK PDF 表单的样本，可能是在 Acrobat 或您喜欢使用的其他工具中填写的？也许有 2 个文件，空表格和填写的表格。
> 
> This would help a lot!这将有很大帮助！
> 
> Thank you so much!非常感谢！

**Comment by dingyaguang117** [comment]
@hhrutter @mdfgzh Hi， after I set the      needAppearances=true， It works at Chrome， Adobe Acrobat…

I will try to fill a pdf by Acrobat later，and then share the two files.

**Comment by hhrutter** [comment]
This should be fixed with the latest commit!
