### ISSUE TITLE
Panic during bounding box calculation for watermark

### ISSUE THREAD

**Issue by vsenko** [pdfcpu/pdfcpu#990]
Watermark generation code can panic here: https://github.com/pdfcpu/pdfcpu/blob/96c3c3753cc9a8896173c6be9ffffa0b0cf13e64/pkg/pdfcpu/model/watermark.go#L250

Looks like for some PDFs `wm.bbPDF` can be `nil` here.
```go
	if wm.IsPDF() {
		wm.bbPDF = wm.PdfRes[wm.PdfPageNrSrc].Bb
		if wm.MultiStamp() {
			i := wm.PdfResIndex(pageNr)
			wm.bbPDF = wm.PdfRes[i].Bb
		}
		wm.Width = int(wm.bbPDF.Width())
		wm.Height = int(wm.bbPDF.Height())
		bb = wm.bbPDF.CroppedCopy(0)
	}
```

Example of a partial trace:
```
        /github.com/pdfcpu/pdfcpu/pkg/pdfcpu/stamp.go:1643 +0x27b
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.AddWatermarks(0xc0019e4bd0, 0xc00029aff0, 0xc000145908)
        /github.com/pdfcpu/pdfcpu/pkg/pdfcpu/stamp.go:1404 +0x2ad
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.addPageWatermark(_, _, {0x0, 0x2, {0xc00012eb10, 0x22}, {0x0, 0x0}, {0xcfd798, 0xc001d87aa0}, ...})
        /github.com/pdfcpu/pdfcpu/pkg/pdfcpu/stamp.go:1017 +0xa5
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.createForm(0xc0019e4bd0, 0x2, 0x4, 0xc000277030, 0x0)
        /github.com/pdfcpu/pdfcpu/pkg/pdfcpu/stamp.go:1005 +0xa9
github.com/pdfcpu/pdfcpu/pkg/pdfcpu.calcFormBoundingBox(0xc000276490?, {0xcfaee0?, 0xc001d867e0?}, {0xc000587410?, 0x0?}, 0x30?, 0xc0002764d8?, 0x40e205?)
        /github.com/pdfcpu/pdfcpu/pkg/pdfcpu/model/watermark.go:250 +0x203
github.com/pdfcpu/pdfcpu/pkg/pdfcpu/model.(*Watermark).CalcBoundingBox(0xc000277030, 0x2)
goroutine 924 [running]:
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x974443]
panic: runtime error: invalid memory address or nil pointer dereference
: dereferenceObject: problem dereferencing stream 24: pdfcpu: loadEncodedStreamContent: missing streamLength
```

Straightforward fix:

```go
	if wm.IsPDF() {
		wm.bbPDF = wm.PdfRes[wm.PdfPageNrSrc].Bb
		if wm.MultiStamp() {
			i := wm.PdfResIndex(pageNr)
			wm.bbPDF = wm.PdfRes[i].Bb
		}

		if wm.bbPDF != nil {
			wm.Width = int(wm.bbPDF.Width())
			wm.Height = int(wm.bbPDF.Height())
			bb = wm.bbPDF.CroppedCopy(0)
		}
	}
```

Unfortunately I can't provide a sample PDF.

Tested on the latest commit on Debian bookworm.

**Comment by hhrutter** [comment]
Does your inputfile pass validation?

Where is this coming from:
`: dereferenceObject: problem dereferencing stream 24: pdfcpu: loadEncodedStreamContent: missing streamLength`

**Comment by vsenko** [comment]
> Does your inputfile pass validation?

Yes, it does:
```
validating(mode=relaxed) xxx.pdf ...
validating URIs..

validation ok
```

> Where is this coming from:
>> : dereferenceObject: problem dereferencing stream 24: pdfcpu: loadEncodedStreamContent: missing streamLength

Ooops, this line is an extra, it was generated by another operation, just skip it.

**Comment by vsenko** [comment]
> Does your inputfile pass validation?

And with strict mode too:
```
validating(mode=strict) xxx.pdf ...
validating URIs..

validation ok
```

**Comment by hhrutter** [comment]
Setting wm.Width/Height only if wm.bbPDF != nil sounds risky to me.
wm.bbPDF being nil means there was a problem retrieving the mediaBox for your PDF stamp and I think that's where we should start.

Since I cannot reproduce this I put this on hold.
